# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Homework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 7.0'
  pod 'Tabman', '~> 3.0'
  # Pods for Homework

end
